This updates dotfiles and lots of bin scripts.

diff --git a/bin/ax b/bin/ax
--- a/bin/ax
+++ b/bin/ax
@@ -12,32 +12,35 @@
 # one file in the current directory.
 #
 # Noah Spurrier 2010-04-16 23:35:46-07:00
-
+#
 OPT='xf'
 for FILENAME in "$@"; do
 	case "${FILENAME}" in
-	*.tgz)     gunzip -c "${FILENAME}" | tar ${OPT} - ;;
+	*.tar.Z)   uncompress -c "${FILENAME}" | tar ${OPT} - ;;
+	*.tar.bz2) bunzip2 -c "${FILENAME}" | tar ${OPT} - ;;
 	*.tar.gz)  gunzip -c "${FILENAME}" | tar ${OPT} - ;;
 	*.tbz2)    bunzip2 -c "${FILENAME}" | tar ${OPT} - ;;
-	*.tar.bz2) bunzip2 -c "${FILENAME}" | tar ${OPT} - ;;
+	*.tgz)     gunzip -c "${FILENAME}" | tar ${OPT} - ;;
 	*.tZ)      uncompress -c "${FILENAME}" | tar ${OPT} - ;;
-	*.tar.Z)   uncompress -c "${FILENAME}" | tar ${OPT} - ;;
-	*.gz)      gunzip "${FILENAME}" ;;
-	*.bz2)     bunzip2 "${FILENAME}" ;;
 	*.Z)       uncompress "${FILENAME}" ;;
+	*.bz2)     bunzip2 "${FILENAME}" ;;
+	*.gz)      gunzip "${FILENAME}" ;;
 	*.tar)     tar ${OPT} ${FILENAME} ;;
-	*.zip)     unzip -lv "${FILENAME}"
-		echo "Unzip this manually with 'unzip ${FILENAME}'"
+	*.zip)
+		mkdir -p ${FILENAME%.zip}
+		cd ${FILENAME%.zip}
+		unzip ../${FILENAME}
+		cd ..
 	;;
 	*.7z)      7z x "${FILENAME}" ;;
 	*.rar)
-		if which unrar >/dev/null; then
+		if type unrar >/dev/null; then
 			unrar x "${FILENAME}"
 		else
 			unrar-free -x "${FILENAME}"
 		fi
 	;;
-	*)      echo "ERROR: Filename, ${FILENAME} was not found" >&2
+	*)      echo "ERROR: Could not find a tool to uncompress ${FILENAME}." >&2
 		exit 1
 	;;
 	esac
diff --git a/bin/test-drive-speed b/bin/test-drive-speed
--- a/bin/test-drive-speed
+++ b/bin/test-drive-speed
@@ -1,11 +1,11 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # test-drive-speed
 #
 # DESCRIPTION
 #
-#     This performs a very simple drive speed test. It measures sustained
-#     write and read speed to a 256 MB file.
+#     This performs a very simple drive speed test.
+#     It measures sustained write and read speed to a 256 MB file.
 #
 # AUTHOR
 #
@@ -18,7 +18,7 @@
 #     approved by the Open Source Initiative. For more information vist:
 #         http://opensource.org/licenses/isc-license.txt
 #
-#     Copyright (c) 2010, Noah Spurrier <noah@noah.org>
+#     Copyright (c) 2013, Noah Spurrier <noah@noah.org>
 #
 #     Permission to use, copy, modify, and/or distribute this software for any
 #     purpose with or without fee is hereby granted, provided that the above
@@ -34,58 +34,100 @@
 #
 # VERSION
 #
-#     Version 1
+#     Version 2
 #
 
-# For a 128 MB file use BLOCK_COUNT=16 and BLOCK_SIZE=8388608.
-# For a 256 MB file use BLOCK_COUNT=32 and BLOCK_SIZE=8388608.
-BLOCK_COUNT=32
-BLOCK_SIZE=8388608
+# BLOCK_COUNT selects number of megabytes because BLOCK_SIZE is 1 MB.
+BLOCK_COUNT=256
+BLOCK_SIZE=1048576
 OUTPUT_FILE="junk.bin"
+
+#
+# Upgrade for next version: Use openssl encryption to generate most of
+# the data instead of using urandom for it all. It's about 10 times faster,
+# which will be significant for very large sized junk.bin test file.
+# dd if=/dev/zero bs=${BLOCK_SIZE} count=${BLOCK_COUNT} |
+# openssl enc -aes-256-ctr -pass "pass:$(dd if=/dev/urandom bs=128 count=1 2>/dev/null | base64)" -nosalt > ${OUTPUT_FILE}
+#
+
+if [ -d /dev/shm ]; then
+    echo "= Create source data file in /dev/shm/random.bin ="
+    SOURCE_DATA=/dev/shm/random.bin
+    rm -f ${SOURCE_DATA}
+    dd if=/dev/urandom of=${SOURCE_DATA} bs=${BLOCK_SIZE} count=${BLOCK_COUNT} iflag=fullblock oflag=dsync conv=fdatasync &
+    PIDDD=$!
+    # Give kernel time to update the process table; otherwise 'kill' sometimes fails the first time.
+    sleep 1
+    while kill -USR1 ${PIDDD} 2>/dev/null; do
+        sleep 1
+        # See man page on terminfo(5) for list of terminal capabilities.
+        #     tput cuu1; tput cuu1; tput cuu1; tput ed
+        # Move cursor up three lines and clear to end of screen.
+        /bin/echo -n -e "\e[A\e[A\e[A\e[J"
+    done
+    # Move cursor down three lines.
+    /bin/echo -n -e "\e[A\e[A\e[A"
+else
+    echo "= WARNING: Using /dev/zero for data. Results may skewed by cache or compression. ="
+    SOURCE_DATA=/dev/zero
+fi
 
 sync
 echo "uptime: $(uptime)"
 PWD=$(pwd)
 echo "current directory: ${PWD}"
-CURRENT_DEV=$(df -hT $(pwd) \
+CURRENT_DEV=$(df -hT "${PWD}" \
  | sed -n -e 's/^\(\/dev\/[^[:space:]]\+\).*/\1/p')
+
 if [ "${CURRENT_DEV}" = "" ]; then
-  echo "WARNING: Did not find device associated with current directory."
+    echo "WARNING: Did not find device associated with current directory."
 else
-  echo "mount device: ${CURRENT_DEV}"
-  echo "drive mount options: $(grep ${CURRENT_DEV} /etc/mtab)"
-  if grep ${CURRENT_DEV} /etc/mtab | grep -iq sync; then
-    echo "    WARNING: sync option will effect write speed tests."
-  fi
-  if echo ${CURRENT_DEV} | grep -q /dev/md; then
-    echo "    This device is a sofware RAID configured as follows:"
-    echo -en "        "
-    egrep 'md[0-9]+' /proc/mdstat
-    CURRENT_DEV=$(egrep 'md[0-9]+' /proc/mdstat \
-      |sed -n -e 's/.*[[:space:]]\([a-z]*[0-9]*\)\[.\]$/\1/p')
-    CURRENT_DEV="/dev/${CURRENT_DEV}"
-    echo "    Drive info will be taken from last device in the array."
-  fi
-  # Try `hdparm` otherwise try `lsusb`.
-  if ! DRIVE_INFO=$(hdparm -I ${CURRENT_DEV} | sed -n -e '/^$/d' \
-    -e '0,/Standards:/p' | sed -n -e '$!p'); then
+    echo "mount device: ${CURRENT_DEV}"
+    echo "drive mount options: $(grep ${CURRENT_DEV} /etc/mtab)"
+    if grep ${CURRENT_DEV} /etc/mtab | grep -iq sync; then
+        echo "    WARNING: sync option will effect write speed tests."
+    fi
+    if echo ${CURRENT_DEV} | grep -q /dev/md; then
+        echo "    This device is a sofware RAID configured as follows:"
+        echo -en "        "
+        egrep 'md[0-9]+' /proc/mdstat
+        CURRENT_DEV=$(egrep 'md[0-9]+' /proc/mdstat \
+            |sed -n -e 's/.*[[:space:]]\([a-z]*[0-9]*\)\[.\]$/\1/p')
+        CURRENT_DEV="/dev/${CURRENT_DEV}"
+        echo "    Drive info will be taken from last device in the array."
+    fi
+    # Try `hdparm` otherwise try `lsusb`.
+    if ! DRIVE_INFO=$(hdparm -I ${CURRENT_DEV} | sed -n -e '/^$/d' \
+        -e '0,/Standards:/p' | sed -n -e '$!p'); then
     DRIVE_INFO=$(lsusb)
-  fi
-  DRIVE_INFO=$(echo ${DRIVE_INFO})
-  echo "drive info: ${DRIVE_INFO}"
 fi
+DRIVE_INFO=$(echo ${DRIVE_INFO})
+echo "drive info: ${DRIVE_INFO}"
+fi
+
 echo
-echo "Running test three times..."
+echo "Run test three times..."
+
 for n in 1 2 3; do
-  echo -n "test ${n}: "
-  sync
-  dd if=/dev/zero of=${OUTPUT_FILE} oflag=dsync conv=fdatasync \
-    bs=${BLOCK_SIZE} count=${BLOCK_COUNT} 2>&1|grep "copied"|cut -f1,6 -d" " \
-    |awk '{printf("write: %7.2f MB/s, ",$1/$2/(1024*1024))}'
-  sync
-  dd if=${OUTPUT_FILE} iflag=direct conv=fdatasync of=/dev/null \
-    bs=${BLOCK_SIZE} count=${BLOCK_COUNT} 2>&1|grep "copied"|cut -f1,6 -d" " \
-    |awk '{printf("read:  %7.2f MB/s\n",$1/$2/(1024*1024))}'
-  rm junk.bin
+    echo -n "test ${n}: "
+    sync
+    dd if=${SOURCE_DATA} of=${OUTPUT_FILE} oflag=dsync conv=fdatasync \
+        bs=${BLOCK_SIZE} count=${BLOCK_COUNT} 2>&1 \
+        |grep "copied"|cut -f1,6 -d" " \
+        |awk '{printf("write: %7.2f MB/s, ",$1/$2/(1024*1024))}'
+    sync
+    if [ ! -e /dev/zero ]; then
+        rm ${SOURCE_DATA}
+    fi
+    dd if=${OUTPUT_FILE} iflag=direct conv=fdatasync of=${SOURCE_DATA} \
+        bs=${BLOCK_SIZE} count=${BLOCK_COUNT} 2>&1 \
+        |grep "copied"|cut -f1,6 -d" " \
+        |awk '{printf("read:  %7.2f MB/s\n",$1/$2/(1024*1024))}'
+    rm junk.bin
 done
-# vim:set ft=sh sr et ts=2 sw=2: // See Vim, :help 'modeline'
+
+if [ -e /dev/shm/random.bin ]; then
+    rm ${SOURCE_DATA}
+fi
+
+# vim:set ft=sh sr et ts=4 sw=4: // See Vim, :help 'modeline'
